// Generated by tools/ingest-variants.mjs — do not edit by hand.
// Which scenes have variation photographs, and on which axes.
// See ../../VARIANTS.md.

export const VARIANTS = {
  "portrait": {
    "ap": [
      "wide",
      "mid",
      "deep"
    ],
    "fl": [
      "wide",
      "norm",
      "long"
    ]
  }
};

export const variantFor = (sceneId, axis, step) =>
  (VARIANTS[sceneId]?.[axis] ?? []).includes(step)
    ? `photos/variants/${sceneId}__${axis}-${step}.jpg`
    : null;
