// Generated by tools/ingest-variants.mjs — do not edit by hand.
// Which scenes have variation photographs, and on which axes.
// See ../../VARIANTS.md.

export const VARIANTS = {
  "architecture": {
    "fl": [
      "wide",
      "norm",
      "long"
    ]
  },
  "food": {
    "ap": [
      "wide",
      "mid",
      "deep"
    ]
  },
  "group": {
    "ap": [
      "wide",
      "mid",
      "deep"
    ]
  },
  "indoor": {
    "ap": [
      "wide",
      "mid",
      "deep"
    ]
  },
  "kids": {
    "sh": [
      "fast",
      "mid",
      "slow"
    ]
  },
  "landscape": {
    "fl": [
      "wide",
      "norm",
      "long"
    ]
  },
  "nightcity": {
    "sh": [
      "fast",
      "mid",
      "slow"
    ]
  },
  "panning": {
    "sh": [
      "fast",
      "mid",
      "slow"
    ]
  },
  "portrait": {
    "ap": [
      "wide",
      "mid",
      "deep"
    ],
    "fl": [
      "wide",
      "norm",
      "long"
    ]
  },
  "sports": {
    "sh": [
      "fast",
      "mid",
      "slow"
    ]
  },
  "street": {
    "ap": [
      "wide",
      "mid",
      "deep"
    ],
    "fl": [
      "wide",
      "norm",
      "long"
    ]
  },
  "water": {
    "sh": [
      "fast",
      "mid",
      "slow"
    ]
  }
};

export const variantFor = (sceneId, axis, step) =>
  (VARIANTS[sceneId]?.[axis] ?? []).includes(step)
    ? `photos/variants/${sceneId}__${axis}-${step}.jpg`
    : null;
