// Generated by ios/tools/gen-data.mjs from the web app. Do not edit by hand.
//
// The twelve scenes and the light levels they are written against, taken
// straight from next/js/lessons.js and app/js/data.js so that the two apps
// cannot quietly disagree about what a portrait is shot at.

import Foundation

public extension Light {
  static let all: [Light] = [
    Light(id: "snow", name: "Snow or sand in sun", sub: "Painfully bright, you are squinting", ev: 16),
    Light(id: "harsh-sun", name: "Harsh sun", sub: "Hard-edged shadows", ev: 15),
    Light(id: "hazy-sun", name: "Hazy sun", sub: "Shadows with soft edges", ev: 14),
    Light(id: "overcast", name: "Bright overcast", sub: "Bright white sky, no shadows", ev: 13),
    Light(id: "heavy-cloud", name: "Heavy cloud, open shade", sub: "Grey and flat, or under a tree", ev: 12),
    Light(id: "late-day", name: "Late day", sub: "An hour before sunset", ev: 11),
    Light(id: "sunset", name: "Sunset", sub: "Sun on the horizon", ev: 10),
    Light(id: "blue-hour", name: "Blue hour", sub: "Colour in the sky, sun gone", ev: 9),
    Light(id: "night-street", name: "Lit street at night", sub: "Shop windows, neon, headlights", ev: 8),
    Light(id: "bright-in", name: "Bright indoors", sub: "Big windows, or a lit gym", ev: 7),
    Light(id: "room-night", name: "Ordinary room at night", sub: "Ceiling light on", ev: 6),
    Light(id: "dim-in", name: "Dim indoors", sub: "Lamps only, restaurant, bar", ev: 5),
    Light(id: "candle", name: "Candlelight", sub: "One flame, close", ev: 4),
    Light(id: "moonlit", name: "Moonlit landscape", sub: "Full moon, no other light", ev: -3),
    Light(id: "dark-sky", name: "Dark sky, no moon", sub: "The Milky Way is visible", ev: -6),
  ]
}

public extension Lesson {
  static let all: [Lesson] = [
    Lesson(
      id: "kids",
      name: "Kids & pets",
      blurb: "A child running across the garden.",
      focal: 50,
      aperture: 5.6,
      shutter: 1.0 / 1000,
      tripod: false,
      needsFilter: false,
      lights: ["harsh-sun", "hazy-sun", "overcast", "heavy-cloud"],
      why: Why(lens: "Close enough to fill the frame without standing on top of them.", aperture: "A touch off wide open. At 1/1000 in daylight you still have light to spare, and it buys you a margin on focus you will be glad of.", shutter: "Fast enough to stop a running child dead."),
      axes: [
      .shutter: Steps(fast: 1.0 / 1000, mid: 0.008, slow: 0.03333333333333333)
      ]),
    Lesson(
      id: "portrait",
      name: "Portrait",
      blurb: "One person, and a background that gets out of the way.",
      focal: 105,
      aperture: 4,
      shutter: 1.0 / 1000,
      tripod: false,
      needsFilter: false,
      lights: ["hazy-sun", "overcast", "heavy-cloud", "late-day"],
      why: Why(lens: "The long end, so the background is magnified and the face is not stretched.", aperture: "As wide as this lens opens, which is what softens the background.", shutter: "Fast, which at this aperture is also what keeps the daylight from overwhelming the lowest ISO the camera has."),
      axes: [
      .aperture: Steps(wide: 2, mid: 8, deep: 16),
      .focal: Steps(wide: 24, norm: 50, long: 105)
      ]),
    Lesson(
      id: "group",
      name: "Group photo",
      blurb: "Two rows of people, and everyone wants to be sharp.",
      focal: 35,
      aperture: 5.6,
      shutter: 1.0 / 500,
      tripod: false,
      needsFilter: false,
      lights: ["hazy-sun", "overcast", "heavy-cloud", "late-day"],
      why: Why(lens: "Wide enough to get everyone in without walking backwards into the sea.", aperture: "Stopped down far enough to carry the back row as well as the front.", shutter: "Fast enough for a group that will not quite hold still."),
      axes: [
      .aperture: Steps(wide: 2, mid: 8, deep: 16)
      ]),
    Lesson(
      id: "sports",
      name: "Sports & action",
      blurb: "A football match from the touchline.",
      focal: 105,
      aperture: 5.6,
      shutter: 1.0 / 1000,
      tripod: false,
      needsFilter: false,
      lights: ["harsh-sun", "hazy-sun", "overcast", "heavy-cloud"],
      why: Why(lens: "The longest this lens goes, and honestly it is short for a pitch.", aperture: "Just off wide open, which in daylight still leaves the shutter all the light it needs.", shutter: "A kicked ball moves fast. This is what freezes it."),
      axes: [
      .shutter: Steps(fast: 1.0 / 1000, mid: 0.008, slow: 0.03333333333333333)
      ]),
    Lesson(
      id: "street",
      name: "Street",
      blurb: "A city street, and something happening in it.",
      focal: 35,
      aperture: 5.6,
      shutter: 1.0 / 500,
      tripod: false,
      needsFilter: false,
      lights: ["hazy-sun", "overcast", "heavy-cloud", "late-day", "blue-hour"],
      why: Why(lens: "The classic street length: about what you see without turning your head.", aperture: "Deep enough that anything a few metres away is already sharp.", shutter: "Fast enough for someone walking past you, and fast enough that a wide-ish aperture in daylight does not run out of ISO."),
      axes: [
      .aperture: Steps(wide: 2, mid: 8, deep: 16),
      .focal: Steps(wide: 24, norm: 35, long: 105)
      ]),
    Lesson(
      id: "landscape",
      name: "Landscape",
      blurb: "A view worth stopping the car for.",
      focal: 24,
      aperture: 8,
      shutter: 1.0 / 250,
      tripod: false,
      needsFilter: false,
      lights: ["hazy-sun", "overcast", "heavy-cloud", "late-day", "blue-hour"],
      why: Why(lens: "The wide end, which is what the wide end is for.", aperture: "The sharpest this lens gets, and deep enough to hold the whole view.", shutter: "Nothing is moving, so this is just fast enough for your hands."),
      axes: [
      .focal: Steps(wide: 24, norm: 50, long: 105)
      ]),
    Lesson(
      id: "architecture",
      name: "Architecture",
      blurb: "A building you want to show whole.",
      focal: 24,
      aperture: 8,
      shutter: 1.0 / 500,
      tripod: false,
      needsFilter: false,
      lights: ["harsh-sun", "hazy-sun", "overcast", "heavy-cloud"],
      why: Why(lens: "Wide enough to fit the building in from across the square.", aperture: "Deep, so the near corner and the far one are both sharp.", shutter: "A building is not going anywhere; this is for your hands."),
      axes: [
      .focal: Steps(wide: 24, norm: 50, long: 105)
      ]),
    Lesson(
      id: "indoor",
      name: "Indoors, no flash",
      blurb: "A room, the light that is already in it, and no flash.",
      focal: 35,
      aperture: 4,
      shutter: 1.0 / 125,
      tripod: false,
      needsFilter: false,
      lights: ["bright-in", "room-night", "dim-in"],
      why: Why(lens: "Wide enough for a room you cannot back out of.", aperture: "Wide open. Indoors you need every stop the lens has.", shutter: "About as slow as you can hand-hold and still be sharp."),
      axes: [
      .aperture: Steps(wide: 2, mid: 8, deep: 16)
      ]),
    Lesson(
      id: "food",
      name: "Food & tabletop",
      blurb: "What is in front of you, by the window.",
      focal: 50,
      aperture: 4,
      shutter: 1.0 / 125,
      tripod: false,
      needsFilter: false,
      lights: ["bright-in", "room-night", "dim-in"],
      why: Why(lens: "Close to what your eye sees, so the plate keeps its shape.", aperture: "Wide open, so the plate stands out of the table around it.", shutter: "Enough to be sharp leaning over a table."),
      axes: [
      .aperture: Steps(wide: 2, mid: 8, deep: 16)
      ]),
    Lesson(
      id: "nightcity",
      name: "Night & city",
      blurb: "A skyline after the sun has gone, from a tripod.",
      focal: 24,
      aperture: 16,
      shutter: 1,
      tripod: true,
      needsFilter: false,
      lights: ["night-street", "blue-hour"],
      why: Why(lens: "Wide, for the whole skyline and the road running into it.", aperture: "Right down. On a tripod the depth is free, and it is also what holds the exposure to a whole second without a filter.", shutter: "Long enough for headlights to draw themselves across the frame."),
      axes: [
      .shutter: Steps(fast: 0.03333333333333333, mid: 0.25, slow: 1)
      ]),
    Lesson(
      id: "water",
      name: "Silky water",
      blurb: "A waterfall, turned to smoke. Tripod, and a filter.",
      focal: 24,
      aperture: 11,
      shutter: 1,
      tripod: true,
      needsFilter: true,
      lights: ["overcast", "heavy-cloud", "late-day", "blue-hour"],
      why: Why(lens: "Wide, close in, with a rock in the foreground.", aperture: "Stopped down: it holds the whole stream sharp and burns off some light.", shutter: "A full second. This is the whole trick."),
      axes: [
      .shutter: Steps(fast: 0.002, mid: 0.06666666666666667, slow: 1)
      ]),
    Lesson(
      id: "panning",
      name: "Panning",
      blurb: "Following something past you, so it stays sharp and the world does not.",
      focal: 50,
      aperture: 16,
      shutter: 1.0 / 30,
      tripod: false,
      needsFilter: false,
      lights: ["overcast", "heavy-cloud", "late-day", "blue-hour"],
      why: Why(lens: "Enough reach to stand safely off the road.", aperture: "Right down, and not for depth: a thirtieth of a second in daylight is far more light than the lowest ISO can take.", shutter: "Slow, on purpose. You turn with the subject and the background smears."),
      axes: [
      .shutter: Steps(fast: 0.002, mid: 0.008, slow: 0.03333333333333333)
      ]),
  ]
}
