#!/usr/bin/env node
// Every type name the app uses, checked against every type name that exists.
//
// Three builds in a row have failed on this one thing: a name that is not
// there. Twice an Apple symbol recalled rather than looked up, once a rename
// that left a reference behind. None of them can be caught by parsing, because
// parsing does not resolve names, and none of them can be caught by the Swift
// tests, because the app half of this port has no compiler on this machine.
//
// So: gather the type names declared across both halves, gather the capitalised
// names the app refers to, and subtract. What is left is either a framework
// type, which belongs in known-symbols.txt and has been checked once, or a
// mistake, which is the entire point.
//
//   node ios/tools/check-symbols.mjs            fails on anything unknown
//   node ios/tools/check-symbols.mjs --update   accepts what is there now
//
// Accepting a name is a deliberate act. A name only belongs in that file once
// somebody has confirmed the framework really has it: a compiler that resolved
// it, or Apple's documentation. Running --update to silence a failure without
// looking is how the thing this guards against gets back in.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const KNOWN = join(HERE, 'known-symbols.txt');

const HEADER = `# Framework and standard library names the app is allowed to use.
#
# Generated by check-symbols.mjs --update, but not a dumping ground: a name
# belongs here only once it has been confirmed to exist, either by a compiler
# that resolved it or by Apple's own documentation. Everything currently listed
# has been through one of those two. Running --update to make a failure go away
# without looking at the name puts back exactly the mistake this guards against.
#
`;

/// Swift with the comments and the prose taken out.
///
/// The prose matters: this app is mostly sentences, and every capitalised word
/// in one of them would otherwise look like a type. What cannot be thrown away
/// is the inside of an interpolation, which is real code sitting in the middle
/// of a string, so those are kept and the rest of the string is not.
function code(source) {
  let out = '';
  let at = 0;
  while (at < source.length) {
    const pair = source.slice(at, at + 2);
    if (pair === '//') {
      while (at < source.length && source[at] !== '\n') at += 1;
      continue;
    }
    if (pair === '/*') {
      let depth = 1;
      at += 2;
      while (at < source.length && depth > 0) {
        if (source.slice(at, at + 2) === '/*') { depth += 1; at += 2; continue; }
        if (source.slice(at, at + 2) === '*/') { depth -= 1; at += 2; continue; }
        at += 1;
      }
      out += ' ';
      continue;
    }
    if (source[at] === '"') {
      at += 1;
      while (at < source.length) {
        if (source[at] === '\\' && source[at + 1] === '(') {
          at += 2;
          let depth = 1;
          while (at < source.length && depth > 0) {
            if (source[at] === '(') depth += 1;
            else if (source[at] === ')') { depth -= 1; if (depth === 0) { at += 1; break; } }
            out += source[at];
            at += 1;
          }
          out += ' ';
          continue;
        }
        if (source[at] === '\\') { at += 2; continue; }
        if (source[at] === '"') { at += 1; break; }
        at += 1;
      }
      out += ' ';
      continue;
    }
    out += source[at];
    at += 1;
  }
  return out;
}

function swiftFiles(dir) {
  const found = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) found.push(...swiftFiles(path));
    else if (entry.name.endsWith('.swift')) found.push(path);
  }
  return found;
}

const declared = new Set();
const used = new Map();   // name -> where it was first seen

const APP = swiftFiles(join(ROOT, 'OffAuto'));
const KIT = swiftFiles(join(ROOT, 'OffAutoKit', 'Sources'));

for (const path of [...APP, ...KIT]) {
  const source = code(readFileSync(path, 'utf8'));
  for (const [, name] of source.matchAll(
    /\b(?:struct|class|enum|protocol|actor|extension|typealias|associatedtype)\s+([A-Z]\w*)/g)) {
    declared.add(name);
  }
  // Generic parameters are names too, and are declared where they are written.
  for (const [, list] of source.matchAll(
    /\b(?:struct|class|enum|protocol|actor|func|typealias)\s+\w+\s*<([^>{]*)>/g)) {
    for (const part of list.split(',')) {
      const name = part.split(':')[0].trim();
      if (/^[A-Z]\w*$/.test(name)) declared.add(name);
    }
  }
}

for (const path of APP) {
  const source = code(readFileSync(path, 'utf8'));
  const lines = source.split('\n');
  lines.forEach((line, index) => {
    // Type names, and the k-prefixed constants Core Foundation and ImageIO use,
    // since one of the three failures this exists to prevent was an invented
    // one of those rather than an invented type.
    for (const [, name] of line.matchAll(/\b((?:[A-Z]|k[A-Z])\w*)\b/g)) {
      if (!used.has(name)) used.set(name, `${path.slice(ROOT.length + 1)}:${index + 1}`);
    }
  });
}

const known = new Set(
  readFileSync(KNOWN, 'utf8').split('\n').map((l) => l.split('#')[0].trim()).filter(Boolean));

const unknown = [...used.keys()].filter((name) => !declared.has(name) && !known.has(name)).sort();

if (process.argv.includes('--update')) {
  const all = [...new Set([...known, ...unknown])].sort();
  writeFileSync(KNOWN, HEADER + all.join('\n') + '\n');
  console.log(`known-symbols.txt now holds ${all.length} names`);
  if (unknown.length) console.log(`added: ${unknown.join(', ')}`);
  process.exit(0);
}

if (unknown.length) {
  console.error('\nNames the app uses that are declared nowhere in this project:\n');
  for (const name of unknown) console.error(`  ${name.padEnd(34)} ${used.get(name)}`);
  console.error('\nEither it is a typo or a rename left behind, or it is a framework type.');
  console.error('If it is a framework type, check it exists and then: node ios/tools/check-symbols.mjs --update\n');
  process.exit(1);
}

console.log(`${used.size} names used, ${declared.size} declared here, ${known.size} known framework types. All accounted for.`);
