// Writes the scene and light tables into Swift, from the web app's own copies.
//
// Transcribing twelve scenes and fifteen light levels by hand is a guaranteed
// way to end up with an app that disagrees with itself in one place nobody
// checks. Generated instead, with the copy collapsed to single spaces, because
// SwiftUI does not collapse whitespace the way a browser does.
//
//   node ios/tools/gen-data.mjs
import { writeFileSync } from 'node:fs';

const next = new URL('../../next/js/', import.meta.url);
const { LESSONS } = await import(new URL('lessons.js', next));
const { LIGHT } = await import(new URL('../../app/js/data.js', import.meta.url));

const tidy = (t) => String(t).replace(/\s+/g, ' ').trim();
const q = (t) => JSON.stringify(tidy(t));
const num = (x) => (Number.isInteger(x) ? `${x}` : `${x}`);

const lights = LIGHT.map((l) =>
  `    Light(id: ${q(l.id)}, name: ${q(l.name)}, sub: ${q(l.sub)}, ev: ${num(l.ev)}),`).join('\n');

const AXIS = { ap: 'aperture', fl: 'focal', sh: 'shutter' };
const scenes = LESSONS.map((s) => {
  const axes = Object.entries(s.axes).map(([axis, spec]) => {
    const steps = Object.entries(spec.steps)
      .map(([step, value]) => `${step}: ${value === 1 / 1000 ? '1.0 / 1000' : num(value)}`);
    return `      .${AXIS[axis]}: Steps(${steps.join(', ')})`;
  }).join(',\n');
  const shutter = Number.isInteger(s.shutter) ? num(s.shutter) : `1.0 / ${Math.round(1 / s.shutter)}`;
  return `    Lesson(
      id: ${q(s.id)},
      name: ${q(s.name)},
      blurb: ${q(s.blurb)},
      focal: ${num(s.focal)},
      aperture: ${num(s.aperture)},
      shutter: ${shutter},
      tripod: ${Boolean(s.tripod)},
      needsFilter: ${Boolean(s.nd)},
      lights: [${s.lights.map(q).join(', ')}],
      why: Why(lens: ${q(s.why.focal)}, aperture: ${q(s.why.aperture)}, shutter: ${q(s.why.shutter)}),
      axes: [
${axes}
      ]),`;
}).join('\n');

const swift = `// Generated by ios/tools/gen-data.mjs from the web app. Do not edit by hand.
//
// The twelve scenes and the light levels they are written against, taken
// straight from next/js/lessons.js and app/js/data.js so that the two apps
// cannot quietly disagree about what a portrait is shot at.

import Foundation

public extension Light {
  static let all: [Light] = [
${lights}
  ]
}

public extension Lesson {
  static let all: [Lesson] = [
${scenes}
  ]
}
`;
writeFileSync(new URL('../OffAutoKit/Sources/OffAutoKit/Generated.swift', import.meta.url), swift);
console.log(`Generated.swift: ${LESSONS.length} scenes, ${LIGHT.length} lights`);
